services:
  finance-api:
    image: 273058101644.dkr.ecr.us-east-1.amazonaws.com/finance-api-prod:latest
    build:
      context: .
      platforms:
      - "linux/amd64"
    hostname: finance-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_PORT
      - VITE_FINANCE_API_URL
      - VITE_FINANCE_URL
      - PG_DB_URL
      - SUPERTOKENS_URI
      - SUPERTOKENS_API_KEY
    ports:
      - 3001:3001
    network_mode: host
