FROM node:18-alpine
WORKDIR /usr/src/app
ENV NODE_ENV=
ENV API_PORT=
ENV VITE_FINANCE_API_URL=
ENV VITE_FINANCE_URL=
ENV PG_DB_URL=
ENV SUPERTOKENS_URI=
ENV SUPERTOKENS_API_KEY=
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3001
CMD ["npm", "run", "start"]
