# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/mortgages', type: :request do
  let!(:user) { create(:user) }
  # This should return the minimal set of attributes required to create a valid
  # Mortgage. As you add validations to Mortgage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      original_balance: 350_000,
      current_balance: 325_000,
      apr: 6.65,
      term: 360,
      payment: 2850
    }
  end

  let(:invalid_attributes) do
    {
      original_balance: nil,
      current_balance: nil,
      apr: 6.65,
      term: 360,
      payment: 2850
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # MortgagesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    headers = { 'Accept' => 'application/json', 'Content-Type' => 'application/json' }
    Devise::JWT::TestHelpers.auth_headers(headers, user)
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      mortgage = user.mortgage = Mortgage.new valid_attributes
      get mortgage_url(mortgage), headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Mortgage' do
        expect do
          post mortgage_url,
               params: { mortgage: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Mortgage, :count).by(1)
      end

      it 'renders a JSON response with the new mortgage' do
        post mortgage_url,
             params: { mortgage: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Mortgage' do
        expect do
          post mortgage_url,
               params: { mortgage: invalid_attributes }, headers: valid_headers, as: :json
        end.not_to change(Mortgage, :count)
      end

      it 'renders a JSON response with errors for the new mortgage' do
        post mortgage_url,
             params: { mortgage: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          original_balance: 347_000,
          apr: 6.64,
          term: 25,
          payment: 3050
        }
      end

      it 'updates the requested mortgage' do
        mortgage = user.mortgage = Mortgage.new valid_attributes
        patch mortgage_url(mortgage),
              params: { mortgage: new_attributes }, headers: valid_headers, as: :json
        mortgage.reload
        expect(mortgage.original_balance).to eq(new_attributes[:original_balance])
      end

      it 'renders a JSON response with the mortgage' do
        mortgage = user.mortgage = Mortgage.new valid_attributes
        patch mortgage_url(mortgage),
              params: { mortgage: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the mortgage' do
        mortgage = user.mortgage = Mortgage.new valid_attributes
        patch mortgage_url(mortgage),
              params: { mortgage: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested mortgage' do
      mortgage = user.mortgage = Mortgage.new valid_attributes
      expect do
        delete mortgage_url(mortgage), headers: valid_headers, as: :json
      end.to change(Mortgage, :count).by(-1)
    end
  end
end
