name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: 8.0
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm run test
      env: 
        SUPERTOKENS_URI: http://localhost
        SUPERTOKENS_API_KEY: somekey
        MONGODB_URI: mongodb://localhost:27017/finance_api_test
