name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - run: createdb -h localhost -p 5432 -U postgres -p postgres finance_api_harmertech_test
    - run: npm run test
      env: 
        SUPERTOKENS_URI: http://localhost
        SUPERTOKENS_API_KEY: somekey
        PG_DB_URL: postgresql://postgres:postgres@localhost:5432/finance_api_harmertech_test
